title: "arda.tc"
url: "https://arda.tc"
baseurl: ""
permalink: /blog/:title/
default_lang: "tr"
languages: ["tr", "en", "de"]
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
